name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1
      - name: Commit Information
        id: commit
        run: |
          echo "commit_id=commit-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - name: Create Patch
        run: |
          bin/ParanormasightChsLocalizationHelper
          compress-archive out/patch/* out/patch-text.zip -force
      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: patch
          path: |
            out/patch/*
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/patch-text.zip"
          bodyFile: README.md
          name: ${{ steps.commit.outputs.commit_message }}
          tag: publish
          token: ${{ secrets.GITHUB_TOKEN }}