name: Build on push

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '*.md'
      - '**/.gitignore'
      - 'files/CharacterTable-*.txt'
      - 'images/'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml